HW1: Popov Ivan
ok-technopolis-autumn-2022/Ivan_Popov pull request #1
Opened 2022-09-30 17:03 UTC by PopovIV

2022-09-30 17:10 UTC, fromanywhere reviewed
На этом этапе тут всё хорошо

Ждем следующую лекцию и будем дорабатывать в этом же pr

2022-10-07 12:33 UTC, fromanywhere commented
Жду здесь aria

2022-10-07 13:36 UTC, PopovIV commented
Внес изменения после первой лекции

2022-10-07 13:50 UTC, fromanywhere requested changes

2022-10-07 13:50 UTC, fromanywhere commented on index.html
> +                <button class="todo_app__select-all" aria-label="Select all tasks"></button>
лучше title, иначе скринридеры прочтут, а просто люди, которые не поняли иконку, не поймут
это относится ко всем кнопкам без текста

2022-10-07 13:50 UTC, fromanywhere commented on index.html
> +            <section class="todo-app__footer-button-group" aria-label="Tasks filter options">
role radiogroup

2022-10-07 14:15 UTC, fromanywhere approved these changes

2022-10-07 14:16 UTC, PopovIV commented on index.html
> +                <button class="todo_app__select-all" aria-label="Select all tasks"></button>
Я поправил
Но тогда получается, что когда буду накидывать CSS, то по-хорошему надо не забыть прописать это же для кнопок удаления задач, потому что текст там заменится на иконку?

2022-10-07 14:18 UTC, merged

2022-10-07 14:26 UTC, fromanywhere commented on index.html
> +                <button class="todo_app__select-all" aria-label="Select all tasks"></button>
так и есть

2022-10-07 14:32 UTC, PopovIV commented on index.html
> +                <button class="todo_app__select-all" aria-label="Select all tasks"></button>
Понял, спасибо!