HW2: Popov Ivan
ok-technopolis-autumn-2022/Ivan_Popov pull request #2
Opened 2022-10-31 15:13 UTC by PopovIV

Немного костыльно приделана пустая задача, надо будет докрутить. Сейчас при добавлении новых заданий, она исчезает, а при большом тексте её размер плывет. Но зато соответствие макету есть.

2022-10-31 16:05 UTC, fromanywhere requested changes

2022-10-31 16:05 UTC, fromanywhere commented on style.css
> +  height: 350px;
Я уже было порадовался, что с первого раза, но нет 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/1042969/199053882-55784c0c-65e0-438c-9f0a-116e8430e946.png">

2022-10-31 16:05 UTC, fromanywhere commented on style.css
> +  align-items: center;
При таком подходе на узком экране левая часть формы недоступна 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/1042969/199054027-8c19e861-4ccc-4619-a372-d2e257169181.png">

2022-11-01 14:46 UTC, PopovIV commented
Вроде удалось избавиться от этих проблем, проверил в хроме и edge, добавление новых тасок и растягивание экрана не приводило к кривому отображению.
В последнем коммите немного подправлен html, я только сейчас заметил, что у меня каждая тудушка была не элементом списка, а отдельным списком, что кажется не очень логичным решением. Видимо, я в первом дз не слишком аккуратно сделал ctrl+c ctrl+v одинакового кода тудушек

2022-11-01 15:07 UTC, fromanywhere approved these changes

2022-11-01 15:26 UTC, merged